name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    - run: |
        echo ${{ steps.setup-chrome.outputs.chrome-path }}
      shell: cmd
