name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
      id: setup-chrome
    - run: |
        "${{ steps.setup-chrome.outputs.chrome-path }}" --headless --dump-dom https://example.com/
      shell: cmd
    - run: |
        "${{ steps.setup-chrome.outputs.chrome-path }}" --headless --dump-dom https://example.com/
